// Données des films - Plus de 50 films réels et connus

const moviesData = [{
        id: 1,
        title: "Inception",
        year: 2010,
        rating: 8.8,
        duration: "2h 28min",
        director: "Christopher Nolan",
        writer: "Christopher Nolan",
        country: "États-Unis",
        genres: ["Action", "Science-fiction", "Drame"],
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page", "Tom Hardy"],
        synopsis: "Dom Cobb est un voleur expérimenté dans l'art dangereux de l'extraction : le vol de secrets précieux au fond de l'esprit pendant l'état de rêve.",
        poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
        boxOffice: "$836.8 million",
        popularity: 95
    },
    {
        id: 2,
        title: "The Dark Knight",
        year: 2008,
        rating: 9.0,
        duration: "2h 32min",
        director: "Christopher Nolan",
        writer: "Jonathan Nolan, Christopher Nolan",
        country: "États-Unis",
        genres: ["Action", "Drame"],
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
        synopsis: "Batman relève le défi le plus grand de sa lutte contre le crime avec l'émergence d'un criminel connu sous le nom de Joker.",
        poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        boxOffice: "$1.005 billion",
        popularity: 98
    },
    {
        id: 3,
        title: "Pulp Fiction",
        year: 1994,
        rating: 8.9,
        duration: "2h 34min",
        director: "Quentin Tarantino",
        writer: "Quentin Tarantino, Roger Avary",
        country: "États-Unis",
        genres: ["Drame", "Action"],
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
        synopsis: "Les vies de deux assassins, d'un boxeur, d'un gangster et de sa femme s'entremêlent dans quatre histoires de violence et de rachat.",
        poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
        boxOffice: "$213.9 million",
        popularity: 92
    },
    {
        id: 4,
        title: "The Shawshank Redemption",
        year: 1994,
        rating: 9.3,
        duration: "2h 22min",
        director: "Frank Darabont",
        writer: "Frank Darabont",
        country: "États-Unis",
        genres: ["Drame"],
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        synopsis: "Deux hommes emprisonnés se lient d'amitié au fil des ans, trouvant réconfort et rédemption grâce à des actes de décence commune.",
        poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
        boxOffice: "$58.5 million",
        popularity: 97
    },
    {
        id: 5,
        title: "Forrest Gump",
        year: 1994,
        rating: 8.8,
        duration: "2h 22min",
        director: "Robert Zemeckis",
        writer: "Eric Roth",
        country: "États-Unis",
        genres: ["Drame", "Romance"],
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
        synopsis: "Les présidences de Kennedy et Johnson, la guerre du Vietnam, le Watergate et d'autres événements historiques se déroulent du point de vue d'un homme de l'Alabama.",
        poster: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
        trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
        boxOffice: "$677.9 million",
        popularity: 94
    },
    {
        id: 6,
        title: "The Matrix",
        year: 1999,
        rating: 8.7,
        duration: "2h 16min",
        director: "Lana & Lilly Wachowski",
        writer: "Lana & Lilly Wachowski",
        country: "États-Unis",
        genres: ["Action", "Science-fiction"],
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
        synopsis: "Un pirate informatique apprend d'un mystérieux rebelle la vérité sur sa réalité et son rôle dans la guerre contre ses contrôleurs.",
        poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
        boxOffice: "$465.3 million",
        popularity: 93
    },
    {
        id: 7,
        title: "The Godfather",
        year: 1972,
        rating: 9.2,
        duration: "2h 55min",
        director: "Francis Ford Coppola",
        writer: "Mario Puzo, Francis Ford Coppola",
        country: "États-Unis",
        genres: ["Drame", "Action"],
        cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
        synopsis: "Le patriarche vieillissant d'une dynastie criminelle transfère le contrôle de son empire clandestin à son fils réticent.",
        poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        trailer: "https://www.youtube.com/watch?v=sY1S34973zA",
        boxOffice: "$250-291 million",
        popularity: 96
    },
    {
        id: 8,
        title: "Avengers: Endgame",
        year: 2019,
        rating: 8.4,
        duration: "3h 2min",
        director: "Anthony & Joe Russo",
        writer: "Christopher Markus, Stephen McFeely",
        country: "États-Unis",
        genres: ["Action", "Science-fiction"],
        cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Scarlett Johansson"],
        synopsis: "Après les événements dévastateurs d'Infinity War, les Avengers restants doivent trouver un moyen de ramener leurs alliés pour un affrontement final avec Thanos.",
        poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
        trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
        boxOffice: "$2.798 billion",
        popularity: 99
    },
    {
        id: 9,
        title: "Interstellar",
        year: 2014,
        rating: 8.6,
        duration: "2h 49min",
        director: "Christopher Nolan",
        writer: "Jonathan Nolan, Christopher Nolan",
        country: "États-Unis",
        genres: ["Science-fiction", "Drame"],
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        synopsis: "Une équipe d'explorateurs voyage à travers un trou de ver dans l'espace pour garantir la survie de l'humanité.",
        poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
        boxOffice: "$701.8 million",
        popularity: 94
    },
    {
        id: 10,
        title: "Parasite",
        year: 2019,
        rating: 8.6,
        duration: "2h 12min",
        director: "Bong Joon Ho",
        writer: "Bong Joon Ho, Han Jin-won",
        country: "Corée du Sud",
        genres: ["Drame", "Comédie"],
        cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
        synopsis: "Une famille pauvre s'infiltre dans la vie d'une famille riche en se faisant passer pour des personnes hautement qualifiées.",
        poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
        boxOffice: "$258.8 million",
        popularity: 91
    },
    {
        id: 11,
        title: "The Lord of the Rings: The Return of the King",
        year: 2003,
        rating: 8.9,
        duration: "3h 21min",
        director: "Peter Jackson",
        writer: "Fran Walsh, Philippa Boyens, Peter Jackson",
        country: "Nouvelle-Zélande",
        genres: ["Action", "Drame"],
        cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Sean Astin"],
        synopsis: "Gandalf et Aragorn dirigent le Monde des Hommes contre l'armée de Sauron pour détourner son regard de Frodon et Sam qui approchent du Mont du Destin.",
        poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        trailer: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
        boxOffice: "$1.142 billion",
        popularity: 95
    },
    {
        id: 12,
        title: "Fight Club",
        year: 1999,
        rating: 8.8,
        duration: "2h 19min",
        director: "David Fincher",
        writer: "Jim Uhls",
        country: "États-Unis",
        genres: ["Drame", "Action"],
        cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
        synopsis: "Un homme souffrant d'insomnie et un vendeur de savon diabolique forment un club de combat souterrain qui évolue en quelque chose de bien plus grand.",
        poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
        boxOffice: "$101.2 million",
        popularity: 92
    },
    {
        id: 13,
        title: "The Silence of the Lambs",
        year: 1991,
        rating: 8.6,
        duration: "1h 58min",
        director: "Jonathan Demme",
        writer: "Ted Tally",
        country: "États-Unis",
        genres: ["Drame", "Horreur"],
        cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
        synopsis: "Une jeune recrue du FBI doit solliciter l'aide d'un tueur en série emprisonné et cannibale pour capturer un autre tueur en série.",
        poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
        trailer: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
        boxOffice: "$272.7 million",
        popularity: 88
    },
    {
        id: 14,
        title: "La La Land",
        year: 2016,
        rating: 8.0,
        duration: "2h 8min",
        director: "Damien Chazelle",
        writer: "Damien Chazelle",
        country: "États-Unis",
        genres: ["Drame", "Romance"],
        cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
        synopsis: "Alors qu'ils naviguent dans leurs carrières à Los Angeles, un pianiste de jazz et une actrice en herbe tombent amoureux.",
        poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
        trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
        boxOffice: "$448.1 million",
        popularity: 87
    },
    {
        id: 15,
        title: "Gladiator",
        year: 2000,
        rating: 8.5,
        duration: "2h 35min",
        director: "Ridley Scott",
        writer: "David Franzoni, John Logan, William Nicholson",
        country: "États-Unis",
        genres: ["Action", "Drame"],
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
        synopsis: "Un général romain déchu devient gladiateur et cherche à se venger du corrupte empereur qui a assassiné sa famille.",
        poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
        trailer: "https://www.youtube.com/watch?v=owK1qxDselE",
        boxOffice: "$460.5 million",
        popularity: 90
    },
    {
        id: 16,
        title: "The Shining",
        year: 1980,
        rating: 8.4,
        duration: "2h 26min",
        director: "Stanley Kubrick",
        writer: "Stanley Kubrick, Diane Johnson",
        country: "États-Unis",
        genres: ["Horreur", "Drame"],
        cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
        synopsis: "Une famille s'installe dans un hôtel isolé où un esprit sinistre influence le père vers la violence.",
        poster: "https://image.tmdb.org/t/p/w500/xazWoLeUyOJXodk2p8S0SbwZTB5.jpg",
        trailer: "https://www.youtube.com/watch?v=FZQvIJxG9Xs",
        boxOffice: "$46 million",
        popularity: 89
    },
    {
        id: 17,
        title: "Toy Story",
        year: 1995,
        rating: 8.3,
        duration: "1h 21min",
        director: "John Lasseter",
        writer: "John Lasseter, Pete Docter, Andrew Stanton",
        country: "États-Unis",
        genres: ["Animation", "Comédie"],
        cast: ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney"],
        synopsis: "Le cowboy Woody a peur de perdre sa place de jouet préféré quand le nouvel astronaut Buzz Lightyear arrive.",
        poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
        trailer: "https://www.youtube.com/watch?v=v-PjgYDrg70",
        boxOffice: "$373.6 million",
        popularity: 88
    },
    {
        id: 18,
        title: "Back to the Future",
        year: 1985,
        rating: 8.5,
        duration: "1h 56min",
        director: "Robert Zemeckis",
        writer: "Robert Zemeckis, Bob Gale",
        country: "États-Unis",
        genres: ["Science-fiction", "Comédie"],
        cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
        synopsis: "Marty McFly voyage dans le temps dans une DeLorean modifiée et cause des ravages dans le passé.",
        poster: "https://image.tmdb.org/t/p/w500/7lyBcpYB0Qt8gYhXYaEZUNlNQAv.jpg",
        trailer: "https://www.youtube.com/watch?v=qvsgGtivCgs",
        boxOffice: "$381.1 million",
        popularity: 89
    },
    {
        id: 19,
        title: "The Lion King",
        year: 1994,
        rating: 8.5,
        duration: "1h 28min",
        director: "Roger Allers, Rob Minkoff",
        writer: "Irene Mecchi, Jonathan Roberts, Linda Woolverton",
        country: "États-Unis",
        genres: ["Animation", "Drame"],
        cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones", "Whoopi Goldberg"],
        synopsis: "Un prince lion trahi et exilé de son royaume apprend le sens de la responsabilité et de la bravoure.",
        poster: "https://image.tmdb.org/t/p/w500/bKPtXn9n4M4s8vvZrbw40mYsefB.jpg",
        trailer: "https://www.youtube.com/watch?v=4sj1MT05lAA",
        boxOffice: "$968.5 million",
        popularity: 91
    },
    {
        id: 20,
        title: "Titanic",
        year: 1997,
        rating: 7.9,
        duration: "3h 14min",
        director: "James Cameron",
        writer: "James Cameron",
        country: "États-Unis",
        genres: ["Drame", "Romance"],
        cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
        synopsis: "Une aristocrate de 17 ans tombe amoureuse d'un artiste pauvre à bord du luxueux RMS Titanic.",
        poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
        trailer: "https://www.youtube.com/watch?v=2e-eXJ6HgkQ",
        boxOffice: "$2.2 billion",
        popularity: 96
    },
    {
        id: 21,
        title: "Jurassic Park",
        year: 1993,
        rating: 8.2,
        duration: "2h 7min",
        director: "Steven Spielberg",
        writer: "Michael Crichton, David Koepp",
        country: "États-Unis",
        genres: ["Action", "Science-fiction"],
        cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough"],
        synopsis: "Un milliardaire philanthrope et une équipe de généticiens créent un parc à thème avec des dinosaures clonés.",
        poster: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
        trailer: "https://www.youtube.com/watch?v=lc0UehYemQA",
        boxOffice: "$1.033 billion",
        popularity: 90
    },
    {
        id: 22,
        title: "The Terminator",
        year: 1984,
        rating: 8.1,
        duration: "1h 47min",
        director: "James Cameron",
        writer: "James Cameron, Gale Anne Hurd",
        country: "États-Unis",
        genres: ["Action", "Science-fiction"],
        cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn", "Paul Winfield"],
        synopsis: "Un soldat humain d'un futur post-apocalyptique est envoyé dans le passé pour sauver une femme d'un cyborg tueur.",
        poster: "https://image.tmdb.org/t/p/w500/q8ffBuxQlYOHrvPniLgCbmKK4Lv.jpg",
        trailer: "https://www.youtube.com/watch?v=k64P4l2Wmeg",
        boxOffice: "$78.4 million",
        popularity: 87
    },
    {
        id: 23,
        title: "Deadpool",
        year: 2016,
        rating: 8.0,
        duration: "1h 48min",
        director: "Tim Miller",
        writer: "Rhett Reese, Paul Wernick",
        country: "États-Unis",
        genres: ["Action", "Comédie"],
        cast: ["Ryan Reynolds", "Morena Baccarin", "Ed Skrein", "T.J. Miller"],
        synopsis: "Un mercenaire se soumet à une expérience qui le laisse avec des pouvoirs de guérison accélérée et adopte l'alter ego Deadpool.",
        poster: "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
        trailer: "https://www.youtube.com/watch?v=ONHBaC-pfsk",
        boxOffice: "$782.6 million",
        popularity: 89
    },
    {
        id: 24,
        title: "The Exorcist",
        year: 1973,
        rating: 8.1,
        duration: "2h 2min",
        director: "William Friedkin",
        writer: "William Peter Blatty",
        country: "États-Unis",
        genres: ["Horreur", "Drame"],
        cast: ["Ellen Burstyn", "Max von Sydow", "Linda Blair", "Jason Miller"],
        synopsis: "Quand une jeune fille est possédée par une entité mystérieuse, sa mère cherche désespérément l'aide de deux prêtres.",
        poster: "https://image.tmdb.org/t/p/w500/4ucLGcXVVSVnsfkGtbLY4XAiusC.jpg",
        trailer: "https://www.youtube.com/watch?v=YDGw1MTEe9k",
        boxOffice: "$441.3 million",
        popularity: 85
    },
    {
        id: 25,
        title: "Spirited Away",
        year: 2001,
        rating: 8.6,
        duration: "2h 5min",
        director: "Hayao Miyazaki",
        writer: "Hayao Miyazaki",
        country: "Japon",
        genres: ["Animation", "Drame"],
        cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Takashi Naito"],
        synopsis: "Pendant sa famille déménage dans la banlieue, une fille de 10 ans s'aventure dans un monde gouverné par des dieux, des sorcières et des esprits.",
        poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        trailer: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
        boxOffice: "$395.8 million",
        popularity: 90
    },
    {
        id: 26,
        title: "The Notebook",
        year: 2004,
        rating: 7.8,
        duration: "2h 3min",
        director: "Nick Cassavetes",
        writer: "Jeremy Leven, Jan Sardi",
        country: "États-Unis",
        genres: ["Romance", "Drame"],
        cast: ["Ryan Gosling", "Rachel McAdams", "James Garner", "Gena Rowlands"],
        synopsis: "Un couple pauvre et passionné est séparé par leur différences sociales dans les années 40.",
        poster: "https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg",
        trailer: "https://www.youtube.com/watch?v=FC6biTjEyZw",
        boxOffice: "$115.6 million",
        popularity: 86
    },
    {
        id: 27,
        title: "The Hangover",
        year: 2009,
        rating: 7.7,
        duration: "1h 40min",
        director: "Todd Phillips",
        writer: "Jon Lucas, Scott Moore",
        country: "États-Unis",
        genres: ["Comédie"],
        cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis", "Justin Bartha"],
        synopsis: "Trois copains se réveillent après une fête de mariage à Las Vegas, sans aucun souvenir et avec le marié disparu.",
        poster: "https://image.tmdb.org/t/p/w500/uluhlXubGu1VGRUeNWC1Q28a7Tw.jpg",
        trailer: "https://www.youtube.com/watch?v=tcdUhdOlz9M",
        boxOffice: "$467.5 million",
        popularity: 84
    },
    {
        id: 28,
        title: "Get Out",
        year: 2017,
        rating: 7.7,
        duration: "1h 44min",
        director: "Jordan Peele",
        writer: "Jordan Peele",
        country: "États-Unis",
        genres: ["Horreur", "Drame"],
        cast: ["Daniel Kaluuya", "Allison Williams", "Catherine Keener", "Bradley Whitford"],
        synopsis: "Un jeune Afro-Américain visite la famille de sa petite amie blanche pour un week-end dans leur maison de campagne.",
        poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
        trailer: "https://www.youtube.com/watch?v=DzfpyUB60YY",
        boxOffice: "$255.5 million",
        popularity: 86
    },
    {
        id: 29,
        title: "The Social Network",
        year: 2010,
        rating: 7.8,
        duration: "2h",
        director: "David Fincher",
        writer: "Aaron Sorkin",
        country: "États-Unis",
        genres: ["Drame"],
        cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake", "Armie Hammer"],
        synopsis: "L'histoire de la création de Facebook et des poursuites judiciaires qui ont suivi.",
        poster: "https://image.tmdb.org/t/p/w500/ok5Wh8385Kgblq9MSU4VGvazeMH.jpg",
        trailer: "https://www.youtube.com/watch?v=lB95KLmpLR4",
        boxOffice: "$224.9 million",
        popularity: 83
    },
    {
        id: 30,
        title: "Blade Runner 2049",
        year: 2017,
        rating: 8.0,
        duration: "2h 44min",
        director: "Denis Villeneuve",
        writer: "Hampton Fancher, Michael Green",
        country: "États-Unis",
        genres: ["Science-fiction", "Drame"],
        cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks"],
        synopsis: "Un jeune Blade Runner découvre un secret enfoui depuis longtemps qui pourrait plonger la société dans le chaos.",
        poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        trailer: "https://www.youtube.com/watch?v=gCcx85zbxz4",
        boxOffice: "$259.2 million",
        popularity: 85
    },
    {
        id: 31,
        title: "Inglourious Basterds",
        year: 2009,
        rating: 8.3,
        duration: "2h 33min",
        director: "Quentin Tarantino",
        writer: "Quentin Tarantino",
        country: "États-Unis",
        genres: ["Action", "Drame"],
        cast: ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent", "Diane Kruger"],
        synopsis: "En France occupée pendant la Seconde Guerre mondiale, un plan pour assassiner des leaders nazis par un groupe de soldats juifs.",
        poster: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        trailer: "https://www.youtube.com/watch?v=KnrRy6kSFF0",
        boxOffice: "$321.5 million",
        popularity: 88
    },
    {
        id: 32,
        title: "Django Unchained",
        year: 2012,
        rating: 8.5,
        duration: "2h 45min",
        director: "Quentin Tarantino",
        writer: "Quentin Tarantino",
        country: "États-Unis",
        genres: ["Action", "Drame"],
        cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"],
        synopsis: "Avec l'aide d'un chasseur de primes allemand, un esclave libéré part à la recherche de sa femme.",
        poster: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
        trailer: "https://www.youtube.com/watch?v=eUdM9vrCbow",
        boxOffice: "$425.4 million",
        popularity: 89
    },
    {
        id: 33,
        title: "The Grand Budapest Hotel",
        year: 2014,
        rating: 8.1,
        duration: "1h 39min",
        director: "Wes Anderson",
        writer: "Wes Anderson",
        country: "États-Unis",
        genres: ["Comédie", "Drame"],
        cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Adrien Brody"],
        synopsis: "Un concierge d'hôtel fait ami avec un employé qui devient son protégé.",
        poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
        trailer: "https://www.youtube.com/watch?v=1Fg5iWmQjwk",
        boxOffice: "$174.6 million",
        popularity: 84
    },
    {
        id: 34,
        title: "Mad Max: Fury Road",
        year: 2015,
        rating: 8.1,
        duration: "2h",
        director: "George Miller",
        writer: "George Miller, Brendan McCarthy, Nick Lathouris",
        country: "Australie",
        genres: ["Action", "Science-fiction"],
        cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
        synopsis: "Dans un monde post-apocalyptique, une femme se rebelle contre un tyran en recherchant sa terre natale avec l'aide d'un groupe de prisonnières.",
        poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        trailer: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
        boxOffice: "$375.2 million",
        popularity: 86
    },
    {
        id: 35,
        title: "Whiplash",
        year: 2014,
        rating: 8.5,
        duration: "1h 46min",
        director: "Damien Chazelle",
        writer: "Damien Chazelle",
        country: "États-Unis",
        genres: ["Drame"],
        cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
        synopsis: "Un jeune batteur de jazz s'efforce de réussir sous la direction d'un instructeur impitoyable.",
        poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        trailer: "https://www.youtube.com/watch?v=7d_jQycdQGo",
        boxOffice: "$49 million",
        popularity: 85
    },
    {
        id: 36,
        title: "The Princess Bride",
        year: 1987,
        rating: 8.0,
        duration: "1h 38min",
        director: "Rob Reiner",
        writer: "William Goldman",
        country: "États-Unis",
        genres: ["Comédie", "Romance"],
        cast: ["Cary Elwes", "Mandy Patinkin", "Robin Wright", "Chris Sarandon"],
        synopsis: "Pendant sa maladie, un jeune garçon écoute une histoire lue par son grand-père.",
        poster: "https://image.tmdb.org/t/p/w500/d8gD7gqDk15q8fN4yQq9kn51cU7.jpg",
        trailer: "https://www.youtube.com/watch?v=O3CIXEAjcc8",
        boxOffice: "$30.9 million",
        popularity: 82
    },
    {
        id: 37,
        title: "A Quiet Place",
        year: 2018,
        rating: 7.5,
        duration: "1h 30min",
        director: "John Krasinski",
        writer: "Bryan Woods, Scott Beck, John Krasinski",
        country: "États-Unis",
        genres: ["Horreur", "Drame"],
        cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds", "Noah Jupe"],
        synopsis: "Dans un monde post-apocalyptique, une famille doit vivre en silence pour éviter des créatures qui chassent par le son.",
        poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
        trailer: "https://www.youtube.com/watch?v=WR7cc5t7tv8",
        boxOffice: "$340.9 million",
        popularity: 84
    },
    {
        id: 38,
        title: "The Incredibles",
        year: 2004,
        rating: 8.0,
        duration: "1h 55min",
        director: "Brad Bird",
        writer: "Brad Bird",
        country: "États-Unis",
        genres: ["Animation", "Action"],
        cast: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson", "Jason Lee"],
        synopsis: "Une famille de super-héros forcés de vivre une vie banale en banlieue est appelée à l'action pour sauver le monde.",
        poster: "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
        trailer: "https://www.youtube.com/watch?v=eZbzbC9285I",
        boxOffice: "$633 million",
        popularity: 85
    },
    {
        id: 39,
        title: "Eternal Sunshine of the Spotless Mind",
        year: 2004,
        rating: 8.3,
        duration: "1h 48min",
        director: "Michel Gondry",
        writer: "Charlie Kaufman, Michel Gondry, Pierre Bismuth",
        country: "États-Unis",
        genres: ["Romance", "Science-fiction"],
        cast: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst", "Mark Ruffalo"],
        synopsis: "Quand leur relation tourne mal, un couple subit une procédure médicale pour s'effacer mutuellement de la mémoire.",
        poster: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
        trailer: "https://www.youtube.com/watch?v=0zFywiAh7N0",
        boxOffice: "$74.1 million",
        popularity: 83
    },
    {
        id: 40,
        title: "Goodfellas",
        year: 1990,
        rating: 8.7,
        duration: "2h 26min",
        director: "Martin Scorsese",
        writer: "Nicholas Pileggi, Martin Scorsese",
        country: "États-Unis",
        genres: ["Drame", "Action"],
        cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
        synopsis: "L'histoire d'un mafieux à demi-irlandais et à demi-sicilien qui monte dans la hiérarchie d'une famille criminelle.",
        poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
        trailer: "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
        boxOffice: "$47 million",
        popularity: 87
    },
    {
        id: 41,
        title: "The Departed",
        year: 2006,
        rating: 8.5,
        duration: "2h 31min",
        director: "Martin Scorsese",
        writer: "William Monahan",
        country: "États-Unis",
        genres: ["Action", "Drame"],
        cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg"],
        synopsis: "Un policier infiltré et un espion de la police s'efforcent de s'identifier mutuellement alors qu'ils s'infiltrent dans un gang irlandais.",
        poster: "https://image.tmdb.org/t/p/w500/tGLO9zw5ZtCeyyEWgbYGgsFxC6i.jpg",
        trailer: "https://www.youtube.com/watch?v=iojhqm0JTW4",
        boxOffice: "$291.5 million",
        popularity: 86
    },
    {
        id: 42,
        title: "The Truman Show",
        year: 1998,
        rating: 8.2,
        duration: "1h 43min",
        director: "Peter Weir",
        writer: "Andrew Niccol",
        country: "États-Unis",
        genres: ["Comédie", "Drame"],
        cast: ["Jim Carrey", "Laura Linney", "Ed Harris", "Noah Emmerich"],
        synopsis: "Un homme dont la vie est une émission de télé réalité ne se rend pas compte que tout autour de lui est faux.",
        poster: "https://image.tmdb.org/t/p/w500/EelZzudHRvJmjWccWscN1S5vmI.jpg",
        trailer: "https://www.youtube.com/watch?v=dlnmQbPGuls",
        boxOffice: "$264.1 million",
        popularity: 84
    },
    {
        id: 43,
        title: "No Country for Old Men",
        year: 2007,
        rating: 8.2,
        duration: "2h 2min",
        director: "Joel & Ethan Coen",
        writer: "Joel & Ethan Coen",
        country: "États-Unis",
        genres: ["Action", "Drame"],
        cast: ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin", "Woody Harrelson"],
        synopsis: "La violence et le chaos s'ensuivent quand un chasseur de primes poursuit un homme qui a détourné une transaction de drogue.",
        poster: "https://image.tmdb.org/t/p/w500/bp9n8TdJFcYMcHt0D7pY9E9CzOe.jpg",
        trailer: "https://www.youtube.com/watch?v=38A__WT3-o0",
        boxOffice: "$171.6 million",
        popularity: 83
    },
    {
        id: 44,
        title: "Black Panther",
        year: 2018,
        rating: 7.3,
        duration: "2h 14min",
        director: "Ryan Coogler",
        writer: "Ryan Coogler, Joe Robert Cole",
        country: "États-Unis",
        genres: ["Action", "Science-fiction"],
        cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira"],
        synopsis: "T'Challa, héritier du royaume caché du Wakanda, doit mener son peuple dans un nouveau futur.",
        poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
        trailer: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
        boxOffice: "$1.347 billion",
        popularity: 88
    },
    {
        id: 45,
        title: "The Wolf of Wall Street",
        year: 2013,
        rating: 8.2,
        duration: "3h",
        director: "Martin Scorsese",
        writer: "Terence Winter",
        country: "États-Unis",
        genres: ["Comédie", "Drame"],
        cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey"],
        synopsis: "Basé sur l'histoire vraie de Jordan Belfort, de sa montée en puissance en tant que courtier riche à sa chute impliquant la criminalité et la corruption.",
        poster: "https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
        trailer: "https://www.youtube.com/watch?v=iszwuX1AK6A",
        boxOffice: "$392 million",
        popularity: 87
    },
    {
        id: 46,
        title: "Gone Girl",
        year: 2014,
        rating: 8.1,
        duration: "2h 29min",
        director: "David Fincher",
        writer: "Gillian Flynn",
        country: "États-Unis",
        genres: ["Drame", "Horreur"],
        cast: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris", "Tyler Perry"],
        synopsis: "Avec la disparition de sa femme ayant attiré l'attention des médias, un homme voit la pression monter quand la police le soupçonne.",
        poster: "https://image.tmdb.org/t/p/w500/qymaJhucquUwjpb8oiqynMeXnID.jpg",
        trailer: "https://www.youtube.com/watch?v=2-_-1nJf8Vg",
        boxOffice: "$369.3 million",
        popularity: 85
    },
    {
        id: 47,
        title: "Coco",
        year: 2017,
        rating: 8.4,
        duration: "1h 45min",
        director: "Lee Unkrich",
        writer: "Adrian Molina, Matthew Aldrich",
        country: "États-Unis",
        genres: ["Animation", "Drame"],
        cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
        synopsis: "Un jeune garçon rêve de devenir musicien malgré l'interdiction de sa famille, et se retrouve dans la Terre des Morts.",
        poster: "https://image.tmdb.org/t/p/w500/eKi8dIrr8voobbaGzDpe8w0PVbC.jpg",
        trailer: "https://www.youtube.com/watch?v=Ga6RYejo6Hk",
        boxOffice: "$807.8 million",
        popularity: 86
    },
    {
        id: 48,
        title: "The Big Lebowski",
        year: 1998,
        rating: 8.1,
        duration: "1h 57min",
        director: "Joel Coen",
        writer: "Joel & Ethan Coen",
        country: "États-Unis",
        genres: ["Comédie", "Drame"],
        cast: ["Jeff Bridges", "John Goodman", "Julianne Moore", "Steve Buscemi"],
        synopsis: "Jeff 'The Dude' Lebowski, erreur d'identité, recherche de rançon, un fœtus et des tapis de bowling.",
        poster: "https://image.tmdb.org/t/p/w500/aHaVjVoXeNanfwUwQ92SG7tosFM.jpg",
        trailer: "https://www.youtube.com/watch?v=cd-go0oBF4Y",
        boxOffice: "$46.7 million",
        popularity: 82
    },
    {
        id: 49,
        title: "Birdman",
        year: 2014,
        rating: 7.7,
        duration: "1h 59min",
        director: "Alejandro González Iñárritu",
        writer: "Alejandro González Iñárritu, Nicolás Giacobone, Alexander Dinelaris, Armando Bo",
        country: "États-Unis",
        genres: ["Comédie", "Drame"],
        cast: ["Michael Keaton", "Zach Galifianakis", "Edward Norton", "Emma Stone"],
        synopsis: "Un acteur illustre lutte pour monter une pièce de Broadway dans les années qui suivent sa célébrité en tant que super-héros.",
        poster: "https://image.tmdb.org/t/p/w500/hUWHsFClX355GBQpHNL4lqH2QkE.jpg",
        trailer: "https://www.youtube.com/watch?v=uJfLoE6hanc",
        boxOffice: "$103.2 million",
        popularity: 81
    },
    {
        id: 50,
        title: "Arrival",
        year: 2016,
        rating: 7.9,
        duration: "1h 56min",
        director: "Denis Villeneuve",
        writer: "Eric Heisserer",
        country: "États-Unis",
        genres: ["Science-fiction", "Drame"],
        cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
        synopsis: "Une linguiste est recrutée par l'armée pour déterminer si des extraterrestres viennent en paix ou sont une menace.",
        poster: "https://image.tmdb.org/t/p/w500/hLudzvGfpi6JlwUnsNhXwKKg4j.jpg",
        trailer: "https://www.youtube.com/watch?v=tFMo3UJ4B4g",
        boxOffice: "$203.4 million",
        popularity: 83
    },
    {
        id: 51,
        title: "Harry Potter and the Philosopher's Stone",
        year: 2001,
        rating: 7.6,
        duration: "2h 32min",
        director: "Chris Columbus",
        writer: "Steve Kloves",
        country: "Royaume-Uni",
        genres: ["Action", "Drame"],
        cast: ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Richard Harris"],
        synopsis: "Un jeune sorcier découvre son héritage magique alors qu'il s'inscrit à l'école de sorcellerie Poudlard.",
        poster: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
        trailer: "https://www.youtube.com/watch?v=VyHV0BRtdxo",
        boxOffice: "$1.018 billion",
        popularity: 88
    },
    {
        id: 52,
        title: "Star Wars: Episode V - The Empire Strikes Back",
        year: 1980,
        rating: 8.7,
        duration: "2h 4min",
        director: "Irvin Kershner",
        writer: "Leigh Brackett, Lawrence Kasdan",
        country: "États-Unis",
        genres: ["Action", "Science-fiction"],
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"],
        synopsis: "Après la destruction de l'Étoile de la Mort, l'Empire poursuit les rebelles à travers la galaxie.",
        poster: "https://image.tmdb.org/t/p/w500/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
        trailer: "https://www.youtube.com/watch?v=JNwNXF9Y6kY",
        boxOffice: "$538.4 million",
        popularity: 90
    },
    {
        id: 53,
        title: "The Green Mile",
        year: 1999,
        rating: 8.6,
        duration: "3h 9min",
        director: "Frank Darabont",
        writer: "Frank Darabont",
        country: "États-Unis",
        genres: ["Drame"],
        cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Bonnie Hunt"],
        synopsis: "Les événements surnaturels qui se produisent sur le couloir de la mort d'une prison dans les années 1930.",
        poster: "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
        trailer: "https://www.youtube.com/watch?v=Ki4haFrqSrw",
        boxOffice: "$286.8 million",
        popularity: 87
    },
    {
        id: 54,
        title: "Casablanca",
        year: 1942,
        rating: 8.5,
        duration: "1h 42min",
        director: "Michael Curtiz",
        writer: "Julius J. Epstein, Philip G. Epstein, Howard Koch",
        country: "États-Unis",
        genres: ["Drame", "Romance"],
        cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid", "Claude Rains"],
        synopsis: "Un cafetier cynique doit choisir entre son amour pour une femme et l'aider à son mari résistant à fuir les nazis.",
        poster: "https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg",
        trailer: "https://www.youtube.com/watch?v=BkL9l7qovsE",
        boxOffice: "$3.7 million",
        popularity: 85
    },
    {
        id: 55,
        title: "Psycho",
        year: 1960,
        rating: 8.5,
        duration: "1h 49min",
        director: "Alfred Hitchcock",
        writer: "Joseph Stefano",
        country: "États-Unis",
        genres: ["Horreur", "Drame"],
        cast: ["Anthony Perkins", "Janet Leigh", "Vera Miles", "John Gavin"],
        synopsis: "Une secrétaire phobique vole 40 000 $ à son employeur et fuit, rencontrant un jeune homme sous l'influence de sa mère.",
        poster: "https://image.tmdb.org/t/p/w500/Ai6NqKHKqLZtD9o1rf4jSvdWkZZ.jpg",
        trailer: "https://www.youtube.com/watch?v=Wz719b9QUqY",
        boxOffice: "$50 million",
        popularity: 84
    },
    {
        id: 56,
        title: "The Sixth Sense",
        year: 1999,
        rating: 8.2,
        duration: "1h 47min",
        director: "M. Night Shyamalan",
        writer: "M. Night Shyamalan",
        country: "États-Unis",
        genres: ["Drame", "Horreur"],
        cast: ["Bruce Willis", "Haley Joel Osment", "Toni Collette", "Olivia Williams"],
        synopsis: "Un garçon qui communique avec les esprits recherche l'aide d'un psychologue désemparé.",
        poster: "https://image.tmdb.org/t/p/w500/f6E0ocLTo30bQJq6KXWiItYOy1F.jpg",
        trailer: "https://www.youtube.com/watch?v=3-ZP95NF_Wk",
        boxOffice: "$672.8 million",
        popularity: 86
    },
    {
        id: 57,
        title: "Up",
        year: 2009,
        rating: 8.3,
        duration: "1h 36min",
        director: "Pete Docter",
        writer: "Pete Docter, Bob Peterson, Tom McCarthy",
        country: "États-Unis",
        genres: ["Animation", "Drame"],
        cast: ["Edward Asner", "Jordan Nagai", "John Ratzenberger", "Christopher Plummer"],
        synopsis: "Un vendeur de ballons de 78 ans réalise enfin son rêve de voyager en attachant des milliers de ballons à sa maison.",
        poster: "https://image.tmdb.org/t/p/w500/vpbaStTMt8qqXaEgnOR2EE4DNJk.jpg",
        trailer: "https://www.youtube.com/watch?v=pkqzFUhGPJg",
        boxOffice: "$735.1 million",
        popularity: 85
    }
];

// Note: Certaines URL d'images peuvent ne pas se charger en raison des restrictions CORS
// Dans une application réelle, vous utiliseriez des images hébergées sur votre propre domaine
// ou vous assureriez que le serveur distant autorise l'utilisation des images.